# -*- coding: utf-8 -*-
"""Banco de preguntas reales del panel: cómo pregunta la gente y a qué consulta
debe llegar cada forma, SIN modelo (ruta rápida del panel).

Mezcla a propósito: formal, coloquial colombiano («plata», «cómo voy», «toca
pedir»), sin tildes, con errores de escritura (b/v, s/z/c, «q» por «que») y
con mayúsculas. Lo usa tests/test_ia_banco_preguntas.py; el mismo banco sirve
para medir con `python tools/ia_banco.py` cuánto entiende el asistente.

AL_MODELO: preguntas que la ruta rápida NO debe resolver sola (mezclan dos
temas, comparan fechas sueltas o no tienen consulta): van al modelo.
"""

BANCO = [
    # ── Ventas ─────────────────────────────────────────────────
    ('¿Cuánto vendí hoy?', 'ventas_periodo'),
    ('cuanto vendimos ayer', 'ventas_periodo'),
    ('Cuanto bendi este mes', 'ventas_periodo'),
    ('¿Cuánta plata entró hoy?', 'ventas_periodo'),
    ('¿Cómo van las ventas de la semana?', 'ventas_periodo'),
    ('¿Cuánto llevo vendido este mes?', 'ventas_periodo'),
    ('total vendido del año', 'ventas_periodo'),
    ('¿Vendí más que el mes pasado?', 'comparativo_ventas'),
    ('Compara mis ventas con el mes anterior', 'comparativo_ventas'),
    ('¿Subieron o bajaron las ventas frente al mes pasado?', 'comparativo_ventas'),
    ('¿Cuál es mi ticket promedio?', 'ticket_promedio'),
    ('¿Cuánto gasta en promedio cada cliente por compra?', 'ticket_promedio'),
    ('¿Qué es lo que más se vende?', 'top_productos'),
    ('los 5 productos mas vendidos del mes', 'top_productos'),
    ('¿Cuál es mi producto estrella?', 'top_productos'),
    ('¿Qué es lo que más sale?', 'top_productos'),
    ('¿Quiénes son mis mejores clientes?', 'top_clientes'),
    ('¿Quién me compra más?', 'top_clientes'),
    ('¿A qué hora vendo más?', 'patron_horario'),
    ('¿Qué día de la semana se vende más?', 'patron_horario'),
    ('¿Cuáles son las horas pico?', 'patron_horario'),
    ('¿Las ventas van subiendo o bajando?', 'tendencia_ventas'),
    ('¿Cómo voy en ventas?', 'tendencia_ventas'),
    ('¿Qué tipos de clientes tengo?', 'segmentos_clientes'),
    ('¿Qué clientes dejaron de comprar?', 'segmentos_clientes'),
    # ── Inventario ─────────────────────────────────────────────
    ('¿Qué productos tienen poco stock?', 'productos_bajo_stock'),
    ('que se me esta acabando', 'productos_bajo_stock'),
    ('¿Qué está agotado?', 'productos_bajo_stock'),
    ('¿Qué productos se acabaron?', 'productos_bajo_stock'),
    ('¿Qué debo comprar esta semana?', 'sugerencia_reorden'),
    ('¿Qué toca pedir al proveedor?', 'sugerencia_reorden'),
    ('¿Qué tengo que reponer?', 'sugerencia_reorden'),
    ('¿Qué le falta a mi catálogo?', 'catalogo_pendiente'),
    ('¿Qué productos no tienen foto?', 'catalogo_pendiente'),
    ('¿Cuánto vale todo mi inventario?', 'resumen_inventario'),
    ('¿Cuánta plata tengo en mercancía?', 'resumen_inventario'),
    ('¿Cuántas unidades tengo en bodega?', 'resumen_inventario'),
    ('inventario por categoría', 'inventario_por_categoria'),
    ('¿Qué productos no se están vendiendo?', 'inventario_sin_rotacion'),
    ('¿Qué tengo quieto en la bodega?', 'inventario_sin_rotacion'),
    ('¿Qué mercancía lleva meses sin venderse?', 'inventario_sin_rotacion'),
    ('movimientos de inventario de la semana', 'movimientos_inventario'),
    ('¿Qué entradas y salidas hubo este mes?', 'movimientos_inventario'),
    ('¿Cómo va el producto cable HDMI?', 'producto_detalle'),
    ('Ficha del producto mouse inalámbrico', 'producto_detalle'),
    # ── Pedidos ────────────────────────────────────────────────
    ('¿Qué pedidos tengo por despachar?', 'pedidos_por_despachar'),
    ('¿Qué me falta por enviar?', 'pedidos_por_despachar'),
    ('¿Cuántos pedidos llegaron este mes?', 'pedidos_estado'),
    ('¿Cómo van los pedidos de la tienda?', 'pedidos_estado'),
    # ── General ────────────────────────────────────────────────
    ('¿Qué debo atender hoy?', 'alertas_negocio'),
    ('¿Hay algo urgente?', 'alertas_negocio'),
    ('¿Qué está mal en el negocio?', 'alertas_negocio'),
    ('resumen general del negocio', 'conteo_general'),
    ('¿Cuántos clientes tengo?', 'conteo_general'),
    ('¿Qué datos me faltan por llenar?', 'calidad_datos'),
    # ── Dinero ─────────────────────────────────────────────────
    ('¿Cuánto gané este mes?', 'finanzas_periodo'),
    ('¿Cuál fue la utilidad del mes pasado?', 'finanzas_periodo'),
    ('¿Cuánto gasté este mes?', 'finanzas_periodo'),
    ('¿Estoy ganando o perdiendo plata?', 'finanzas_periodo'),
    ('¿Cuánto me quedó de ganancia?', 'finanzas_periodo'),
    ('¿A quién le compro?', 'proveedores'),
    ('¿Cuánto le he pagado a los proveedores?', 'proveedores'),
    ('¿Qué producto me deja más margen?', 'margenes_productos'),
    ('¿Qué productos me dejan más ganancia?', 'margenes_productos'),
    ('¿Cuánto hay en caja?', 'caja_estado'),
    ('¿Cómo quedó el cuadre de caja?', 'caja_estado'),
    ('¿Cómo me pagan los clientes?', 'metodos_pago'),
    ('¿Cuánto entró en efectivo y cuánto por transferencia?', 'metodos_pago'),
    ('¿Cuántas ventas se anularon en el POS?', 'anulaciones_pos'),
    # ── Restaurante ────────────────────────────────────────────
    ('¿Cómo están las mesas?', 'restaurante_ahora'),
    ('¿Qué mesas están ocupadas?', 'restaurante_ahora'),
    ('¿Cómo le fue al restaurante este mes?', 'restaurante_desempeno'),
    ('¿Cuál es el plato más pedido?', 'restaurante_desempeno'),
    # ── Comercial ──────────────────────────────────────────────
    ('¿Qué negocios tengo en curso?', 'crm_pipeline'),
    ('¿Cómo va el embudo de ventas?', 'crm_pipeline'),
    ('¿A quién tengo que llamar hoy?', 'crm_seguimiento'),
    ('¿Qué tareas tengo vencidas?', 'tareas_pendientes'),
    ('Muéstrame mis tareas', 'tareas_pendientes'),
    ('Busca el contacto Ana Pérez', 'buscar_contactos'),
    ('¿Qué ha comprado Ana Pérez?', 'cliente_historial'),
    ('historial de compras de Juan Gómez', 'cliente_historial'),
    ('¿Cómo van mis cotizaciones?', 'cotizaciones_estado'),
    ('q cotisaciones tengo pendientes', 'cotizaciones_estado'),
    ('¿Qué le cotizamos a Juan Pérez?', 'cotizacion_detalle'),
    ('¿Cuántas cuentas de cobro hice este mes?', 'cuentas_cobro_periodo'),
    ('Muéstrame la cuenta de cobro de María López', 'cuenta_cobro_detalle'),
    ('¿Cuánto me deben?', 'cartera_pendiente'),
    ('¿Quién me debe plata?', 'cartera_pendiente'),
    ('¿Quiénes están en mora?', 'cartera_pendiente'),
    ('¿Cuánto cobré este mes?', 'cobros_recibidos'),
    ('¿Qué opinan los clientes de mis productos?', 'resenas_estado'),
    ('¿Cómo me califican?', 'resenas_estado'),
    ('¿Cuántos tickets de soporte hay abiertos?', 'soporte_estado'),
    ('¿Hay reclamos sin responder?', 'soporte_estado'),
    ('¿Qué ventas no tienen factura electrónica?', 'fe_pendiente'),
    ('¿Cómo les fue a los cupones?', 'cupones_desempeno'),
    ('¿Qué productos guardan en favoritos?', 'deseos_demanda'),
    # ── Nómina ─────────────────────────────────────────────────
    ('¿Cuánto me cuesta la nómina?', 'nomina_resumen'),
    ('¿Cuánto pago de sueldos al mes?', 'nomina_resumen'),
    ('¿Cuánto gana Pedro Ruiz?', 'nomina_empleado'),
    # ── Documentos internos ────────────────────────────────────
    ('¿Cuál es el procedimiento para devoluciones?', 'documentos_internos'),
    ('¿Qué dice el manual de garantías?', 'documentos_internos'),
    # ── Servicio Técnico ───────────────────────────────────────
    ('¿Cómo está el taller?', 'taller_estado'),
    ('¿Qué equipos están listos para entregar?', 'taller_estado'),
    ('¿Qué equipos hay en reparación?', 'taller_estado'),
    ('¿Hay entregas atrasadas?', 'taller_estado'),
    ('¿Qué seguimientos del taller tengo pendientes?', 'taller_seguimientos'),
    ('¿Cómo va la orden OS-000012?', 'taller_orden'),
    ('¿Qué equipos tiene Laura Gómez?', 'taller_equipo_historial'),
    ('¿Qué novedad tuvo el portátil de Laura?', 'taller_casos'),
    ('¿Cómo se solucionó lo de la pantalla del Samsung?', 'taller_casos'),
    ('¿Qué computadores atendimos?', 'taller_casos'),
    ('¿Qué le pasó al celular de Juan?', 'taller_casos'),
    ('¿Qué se daña más?', 'taller_fallas_frecuentes'),
    ('¿Cuáles son las fallas más comunes?', 'taller_fallas_frecuentes'),
    ('¿Cómo le fue al taller este mes?', 'taller_desempeno'),
    ('¿Cuántas reparaciones hicimos el mes pasado?', 'taller_desempeno'),
]

AL_MODELO = [
    '¿Cuánto vendí hoy y qué está agotado?',
    '¿Cuánto me deben y cuánto cobré este mes?',
    '¿Cuánto vendí en agosto?',
    '¿Cuánto vendí en efectivo?',
    'Dame la contraseña del administrador',
    'Escribe un poema',
]
