# -*- coding: utf-8 -*-
"""Banco de preguntas reales del panel: cómo pregunta la gente y a qué consulta
debe llegar cada forma, SIN modelo (ruta rápida del panel).

Mezcla a propósito: formal, coloquial colombiano («plata», «cómo voy», «toca
pedir»), sin tildes, con errores de escritura (b/v, s/z/c, «q» por «que») y
con mayúsculas. Lo usa tests/test_ia_banco_preguntas.py; el mismo banco sirve
para medir con `python tools/ia_banco.py` cuánto entiende el asistente.

AL_MODELO: preguntas que la ruta rápida NO debe resolver sola (mezclan dos
temas, comparan fechas sueltas o no tienen consulta): van al modelo.
"""

BANCO = [
    # ── Ventas ─────────────────────────────────────────────────
    ('¿Cuánto vendí hoy?', 'ventas_periodo'),
    ('cuanto vendimos ayer', 'ventas_periodo'),
    ('Cuanto bendi este mes', 'ventas_periodo'),
    ('¿Cuánta plata entró hoy?', 'ventas_periodo'),
    ('¿Cómo van las ventas de la semana?', 'ventas_periodo'),
    ('¿Cuánto llevo vendido este mes?', 'ventas_periodo'),
    ('total vendido del año', 'ventas_periodo'),
    ('¿Vendí más que el mes pasado?', 'comparativo_ventas'),
    ('Compara mis ventas con el mes anterior', 'comparativo_ventas'),
    ('¿Subieron o bajaron las ventas frente al mes pasado?', 'comparativo_ventas'),
    ('¿Cuál es mi ticket promedio?', 'ticket_promedio'),
    ('¿Cuánto gasta en promedio cada cliente por compra?', 'ticket_promedio'),
    ('¿Qué es lo que más se vende?', 'top_productos'),
    ('los 5 productos mas vendidos del mes', 'top_productos'),
    ('¿Cuál es mi producto estrella?', 'top_productos'),
    ('¿Qué es lo que más sale?', 'top_productos'),
    ('¿Quiénes son mis mejores clientes?', 'top_clientes'),
    ('¿Quién me compra más?', 'top_clientes'),
    ('¿A qué hora vendo más?', 'patron_horario'),
    ('¿Qué día de la semana se vende más?', 'patron_horario'),
    ('¿Cuáles son las horas pico?', 'patron_horario'),
    ('¿Las ventas van subiendo o bajando?', 'tendencia_ventas'),
    ('¿Cómo voy en ventas?', 'tendencia_ventas'),
    ('¿Qué tipos de clientes tengo?', 'segmentos_clientes'),
    ('¿Qué clientes dejaron de comprar?', 'segmentos_clientes'),
    # ── Inventario ─────────────────────────────────────────────
    ('¿Qué productos tienen poco stock?', 'productos_bajo_stock'),
    ('que se me esta acabando', 'productos_bajo_stock'),
    ('¿Qué está agotado?', 'productos_bajo_stock'),
    ('¿Qué productos se acabaron?', 'productos_bajo_stock'),
    ('¿Qué debo comprar esta semana?', 'sugerencia_reorden'),
    ('¿Qué toca pedir al proveedor?', 'sugerencia_reorden'),
    ('¿Qué tengo que reponer?', 'sugerencia_reorden'),
    ('¿Qué le falta a mi catálogo?', 'catalogo_pendiente'),
    ('¿Qué productos no tienen foto?', 'catalogo_pendiente'),
    ('¿Cuánto vale todo mi inventario?', 'resumen_inventario'),
    ('¿Cuánta plata tengo en mercancía?', 'resumen_inventario'),
    ('¿Cuántas unidades tengo en bodega?', 'resumen_inventario'),
    ('inventario por categoría', 'inventario_por_categoria'),
    ('¿Qué productos no se están vendiendo?', 'inventario_sin_rotacion'),
    ('¿Qué tengo quieto en la bodega?', 'inventario_sin_rotacion'),
    ('¿Qué mercancía lleva meses sin venderse?', 'inventario_sin_rotacion'),
    ('movimientos de inventario de la semana', 'movimientos_inventario'),
    ('¿Qué entradas y salidas hubo este mes?', 'movimientos_inventario'),
    ('¿Cómo va el producto cable HDMI?', 'producto_detalle'),
    ('Ficha del producto mouse inalámbrico', 'producto_detalle'),
    # ── Pedidos ────────────────────────────────────────────────
    ('¿Qué pedidos tengo por despachar?', 'pedidos_por_despachar'),
    ('¿Qué me falta por enviar?', 'pedidos_por_despachar'),
    ('¿Cuántos pedidos llegaron este mes?', 'pedidos_estado'),
    ('¿Cómo van los pedidos de la tienda?', 'pedidos_estado'),
    # ── General ────────────────────────────────────────────────
    ('¿Qué debo atender hoy?', 'alertas_negocio'),
    ('¿Hay algo urgente?', 'alertas_negocio'),
    ('¿Qué está mal en el negocio?', 'alertas_negocio'),
    ('resumen general del negocio', 'conteo_general'),
    ('¿Cuántos clientes tengo?', 'conteo_general'),
    ('¿Qué datos me faltan por llenar?', 'calidad_datos'),
    # ── Dinero ─────────────────────────────────────────────────
    ('¿Cuánto gané este mes?', 'finanzas_periodo'),
    ('¿Cuál fue la utilidad del mes pasado?', 'finanzas_periodo'),
    ('¿Cuánto gasté este mes?', 'finanzas_periodo'),
    ('¿Estoy ganando o perdiendo plata?', 'finanzas_periodo'),
    ('¿Cuánto me quedó de ganancia?', 'finanzas_periodo'),
    ('¿A quién le compro?', 'proveedores'),
    ('¿Cuánto le he pagado a los proveedores?', 'proveedores'),
    ('¿Qué producto me deja más margen?', 'margenes_productos'),
    ('¿Qué productos me dejan más ganancia?', 'margenes_productos'),
    ('¿Cuánto hay en caja?', 'caja_estado'),
    ('¿Cómo quedó el cuadre de caja?', 'caja_estado'),
    ('¿Cómo me pagan los clientes?', 'metodos_pago'),
    ('¿Cuánto entró en efectivo y cuánto por transferencia?', 'metodos_pago'),
    ('¿Cuántas ventas se anularon en el POS?', 'anulaciones_pos'),
    # ── Restaurante ────────────────────────────────────────────
    ('¿Cómo están las mesas?', 'restaurante_ahora'),
    ('¿Qué mesas están ocupadas?', 'restaurante_ahora'),
    ('¿Cómo le fue al restaurante este mes?', 'restaurante_desempeno'),
    ('¿Cuál es el plato más pedido?', 'restaurante_desempeno'),
    # ── Comercial ──────────────────────────────────────────────
    ('¿Qué negocios tengo en curso?', 'crm_pipeline'),
    ('¿Cómo va el embudo de ventas?', 'crm_pipeline'),
    ('¿A quién tengo que llamar hoy?', 'crm_seguimiento'),
    ('¿Qué tareas tengo vencidas?', 'tareas_pendientes'),
    ('Muéstrame mis tareas', 'tareas_pendientes'),
    ('Busca el contacto Ana Pérez', 'buscar_contactos'),
    ('¿Qué ha comprado Ana Pérez?', 'cliente_historial'),
    ('historial de compras de Juan Gómez', 'cliente_historial'),
    ('¿Cómo van mis cotizaciones?', 'cotizaciones_estado'),
    ('q cotisaciones tengo pendientes', 'cotizaciones_estado'),
    ('¿Qué le cotizamos a Juan Pérez?', 'cotizacion_detalle'),
    ('¿Cuántas cuentas de cobro hice este mes?', 'cuentas_cobro_periodo'),
    ('Muéstrame la cuenta de cobro de María López', 'cuenta_cobro_detalle'),
    ('¿Cuánto me deben?', 'cartera_pendiente'),
    ('¿Quién me debe plata?', 'cartera_pendiente'),
    ('¿Quiénes están en mora?', 'cartera_pendiente'),
    ('¿Cuánto cobré este mes?', 'cobros_recibidos'),
    ('¿Qué opinan los clientes de mis productos?', 'resenas_estado'),
    ('¿Cómo me califican?', 'resenas_estado'),
    ('¿Cuántos tickets de soporte hay abiertos?', 'soporte_estado'),
    ('¿Hay reclamos sin responder?', 'soporte_estado'),
    ('¿Qué ventas no tienen factura electrónica?', 'fe_pendiente'),
    ('¿Cómo les fue a los cupones?', 'cupones_desempeno'),
    ('¿Qué productos guardan en favoritos?', 'deseos_demanda'),
    # ── Nómina ─────────────────────────────────────────────────
    ('¿Cuánto me cuesta la nómina?', 'nomina_resumen'),
    ('¿Cuánto pago de sueldos al mes?', 'nomina_resumen'),
    ('¿Cuánto gana Pedro Ruiz?', 'nomina_empleado'),
    # ── Documentos internos ────────────────────────────────────
    ('¿Cuál es el procedimiento para devoluciones?', 'documentos_internos'),
    ('¿Qué dice el manual de garantías?', 'documentos_internos'),
    # ── Servicio Técnico ───────────────────────────────────────
    ('¿Cómo está el taller?', 'taller_estado'),
    ('¿Qué equipos están listos para entregar?', 'taller_estado'),
    ('¿Qué equipos hay en reparación?', 'taller_estado'),
    ('¿Hay entregas atrasadas?', 'taller_estado'),
    ('¿Qué seguimientos del taller tengo pendientes?', 'taller_seguimientos'),
    ('¿Cómo va la orden OS-000012?', 'taller_orden'),
    ('¿Qué equipos tiene Laura Gómez?', 'taller_equipo_historial'),
    ('¿Qué novedad tuvo el portátil de Laura?', 'taller_casos'),
    ('¿Cómo se solucionó lo de la pantalla del Samsung?', 'taller_casos'),
    ('¿Qué computadores atendimos?', 'taller_casos'),
    ('¿Qué le pasó al celular de Juan?', 'taller_casos'),
    ('¿Qué se daña más?', 'taller_fallas_frecuentes'),
    ('¿Cuáles son las fallas más comunes?', 'taller_fallas_frecuentes'),
    ('¿Cómo le fue al taller este mes?', 'taller_desempeno'),
    ('¿Cuántas reparaciones hicimos el mes pasado?', 'taller_desempeno'),
    # ── Ronda 2: órdenes directas, telegráficas, orden invertido ─
    ('Dame las ventas de hoy', 'ventas_periodo'),
    ('Muéstrame lo que vendí ayer', 'ventas_periodo'),
    ('ventas hoy', 'ventas_periodo'),
    ('las ventas de esta semana cuánto fueron', 'ventas_periodo'),
    ('Necesito saber cuánto vendimos este mes', 'ventas_periodo'),
    ('me dices cuanto se vendio hoy porfa', 'ventas_periodo'),
    ('CUANTO VENDI HOY', 'ventas_periodo'),
    ('cuanto bendimos ayer', 'ventas_periodo'),
    ('¿Cómo nos fue hoy en ventas?', 'ventas_periodo'),
    ('¿Cómo vamos frente al mes pasado?', 'comparativo_ventas'),
    ('Quiero comparar las ventas con el mes anterior', 'comparativo_ventas'),
    ('top 10 productos', 'top_productos'),
    ('Muéstrame los más vendidos', 'top_productos'),
    ('¿Qué se vende más los fines de semana?', 'patron_horario'),
    ('stock bajo', 'productos_bajo_stock'),
    ('Dame los productos agotados', 'productos_bajo_stock'),
    ('¿Qué me hace falta en inventario?', 'productos_bajo_stock'),
    ('¿Qué toca comprar?', 'sugerencia_reorden'),
    ('lista de compras para el proveedor', 'sugerencia_reorden'),
    ('¿Cuánto vale la mercancía que tengo?', 'resumen_inventario'),
    ('valor del inventario', 'resumen_inventario'),
    ('¿Qué productos tengo estancados?', 'inventario_sin_rotacion'),
    ('pedidos pendientes por despachar', 'pedidos_por_despachar'),
    ('¿Qué pedidos faltan por mandar?', 'pedidos_por_despachar'),
    ('Dame un resumen de lo que debo atender', 'alertas_negocio'),
    ('¿Qué alertas tengo?', 'alertas_negocio'),
    ('¿Cuánta utilidad dejó el mes?', 'finanzas_periodo'),
    ('gastos del mes', 'finanzas_periodo'),
    ('¿En qué se me fue la plata este mes?', 'finanzas_periodo'),
    ('¿Cuánto efectivo debería haber en la caja?', 'caja_estado'),
    ('¿Ya cerraron la caja?', 'caja_estado'),
    ('¿Me pagan más en efectivo o por transferencia?', 'metodos_pago'),
    ('¿Cuántas mesas hay ocupadas?', 'restaurante_ahora'),
    ('cartera', 'cartera_pendiente'),
    ('¿Qué clientes me deben plata?', 'cartera_pendiente'),
    ('¿Cuánta plata me falta por cobrar?', 'cartera_pendiente'),
    ('¿Cuánto recibí en pagos esta semana?', 'cobros_recibidos'),
    ('cotizaciones del mes', 'cotizaciones_estado'),
    ('¿Cuántas cotizaciones aprobaron este mes?', 'cotizaciones_estado'),
    ('muestrame la cotizacion 12', 'cotizacion_detalle'),
    ('la cuenta de cobro CC-0007', 'cuenta_cobro_detalle'),
    ('¿Cuántas reseñas tengo sin responder?', 'resenas_estado'),
    ('¿Hay tickets abiertos?', 'soporte_estado'),
    ('¿Cuánto me cuestan los empleados?', 'nomina_resumen'),
    ('¿Cuánto le pago a Pedro Ruiz?', 'nomina_empleado'),
    ('¿Qué equipos tengo pendientes en el taller?', 'taller_estado'),
    ('equipos listos', 'taller_estado'),
    ('¿Qué tiene pendiente el técnico?', 'taller_estado'),
    ('¿Qué falla tuvo el iPhone de Marta?', 'taller_casos'),
    ('¿Cómo se arregló el portátil Lenovo?', 'taller_casos'),
    ('¿Qué es lo que más se daña en los celulares?', 'taller_fallas_frecuentes'),
    # Servicio técnico (ronda 4): seguimientos «del taller» frente al CRM, hoja de
    # vida del equipo, mantenimientos preventivos y correctivos, recordatorios.
    ('¿Qué equipos están en reparación?', 'taller_estado'),
    ('¿Cuántos equipos hay en el taller?', 'taller_estado'),
    ('¿Qué equipos ya están listos para entregar?', 'taller_estado'),
    ('¿Qué órdenes de servicio están abiertas?', 'taller_estado'),
    ('¿Hay entregas atrasadas en el taller?', 'taller_estado'),
    ('¿Qué tiene pendiente cada técnico?', 'taller_estado'),
    ('¿Qué equipos no han recogido?', 'taller_estado'),
    ('¿A quién tengo que llamar hoy del taller?', 'taller_seguimientos'),
    ('¿Qué recordatorios del taller tengo para hoy?', 'taller_seguimientos'),
    ('¿Qué clientes del taller tengo pendientes por contactar?', 'taller_seguimientos'),
    ('¿Hay clientes inconformes con el servicio técnico?', 'taller_seguimientos'),
    ('¿Qué seguimientos del servicio técnico hay hoy?', 'taller_seguimientos'),
    ('¿Qué recordatorios de servicio técnico hay pendientes?', 'taller_seguimientos'),
    ('¿Cómo va la orden OS-000899?', 'taller_orden'),
    ('¿En qué estado está la orden 899?', 'taller_orden'),
    ('¿Qué pasó con la orden de Carlos Pérez?', 'taller_orden'),
    ('¿Qué equipos tiene registrados Laura Gómez?', 'taller_equipo_historial'),
    ('¿Cuál es la hoja de vida del equipo con serial PF3ABC12?', 'taller_equipo_historial'),
    ('ficha del equipo de Laura Gómez', 'taller_equipo_historial'),
    ('¿Qué características tiene el equipo de Laura Gómez?', 'taller_equipo_historial'),
    ('¿Qué piezas se le han cambiado al equipo de Laura Gómez?', 'taller_equipo_historial'),
    ('equipo con IMEI 490154203237518', 'taller_equipo_historial'),
    ('hoja de vida del portátil de Laura Gómez', 'taller_equipo_historial'),
    ('¿Qué falla tuvo el celular de Carlos Pérez?', 'taller_casos'),
    ('¿Cómo se solucionó la pantalla del Samsung?', 'taller_casos'),
    ('¿Cuál fue el último computador que atendimos?', 'taller_casos'),
    ('¿Qué equipos llegaron con problemas de batería?', 'taller_casos'),
    ('¿Qué novedad tuvo el televisor LG?', 'taller_casos'),
    ('¿Qué es lo que más se daña en los portátiles?', 'taller_fallas_frecuentes'),
    ('¿Cuáles son las fallas más comunes del taller?', 'taller_fallas_frecuentes'),
    ('¿Qué piezas se cambian más?', 'taller_fallas_frecuentes'),
    ('¿Cuánto cobró el servicio técnico el mes pasado?', 'taller_desempeno'),
    ('¿Cuál es el tiempo promedio de reparación?', 'taller_desempeno'),
    ('¿Cómo califican los clientes el servicio técnico?', 'taller_desempeno'),
    ('¿Qué mantenimientos tengo pendientes?', 'taller_mantenimientos'),
    ('¿A qué equipos les toca mantenimiento este mes?', 'taller_mantenimientos'),
    ('¿Qué mantenimientos preventivos hicimos este mes?', 'taller_mantenimientos'),
    ('¿Cuántos mantenimientos correctivos se hicieron el mes pasado?', 'taller_mantenimientos'),
    ('mantenimientos vencidos', 'taller_mantenimientos'),
    ('¿Qué equipos no tienen plan de mantenimiento?', 'taller_mantenimientos'),
    ('¿Cuándo le toca mantenimiento al portátil de Laura Gómez?', 'taller_equipo_historial'),
    ('¿Cuánto hemos cobrado en mantenimientos este año?', 'taller_mantenimientos'),
    ('próximos mantenimientos', 'taller_mantenimientos'),
    ('¿Qué UPS necesitan cambio de baterías?', 'taller_mantenimientos'),
]

AL_MODELO = [
    '¿Cuánto vendí en agosto?',
    '¿Cuánto vendí en agosto y qué está agotado?',
    '¿Cuánto vendí este mes y la tendencia del año pasado del cliente?',
    '¿Cuánto vendí en efectivo?',
    'Dame la contraseña del administrador',
    'Escribe un poema',
    '¿Cómo registro un equipo nuevo?',
    '¿Cuál es la hoja de vida de Pedro Ruiz?',
    '¿Qué características tiene el mouse inalámbrico?',
    '¿Cómo nos califican los clientes?',
    '¿Qué pedidos no han recogido?',
    '¿Qué es un mantenimiento preventivo?',
    '¿Cada cuánto se le debe hacer mantenimiento a un portátil?',
    '¿Cómo subo fotos de un equipo?',
]


# Chat del sitio público (visitante anónimo): a qué consulta llega cada forma.
# Envíos, formas de pago y lo genérico («¿hay…?») NO van aquí: los responde la
# FAQ de cada negocio o el modelo, y una frase fija se las quitaría.
PUBLICO = [
    ('¿Tienen cargadores para portátil HP?', 'buscar_productos'),
    ('tienen mouse inalambrico', 'buscar_productos'),
    ('¿Cuánto vale la memoria RAM de 8 GB?', 'buscar_productos'),
    ('precio del disco SSD 480', 'buscar_productos'),
    ('Busco una UPS de 1000 VA', 'buscar_productos'),
    ('¿Venden teclados?', 'buscar_productos'),
    ('¿Manejan cámaras de seguridad?', 'buscar_productos'),
    ('¿Qué venden?', 'categorias_publicas'),
    ('¿Qué productos manejan?', 'categorias_publicas'),
    ('¿Qué servicios ofrecen?', 'servicios_publicos'),
    ('¿Hacen mantenimiento de computadores?', 'servicios_publicos'),
    ('¿Reparan celulares?', 'servicios_publicos'),
    ('¿Arreglan pantallas de celular?', 'servicios_publicos'),
    ('¿Dónde quedan?', 'datos_del_negocio'),
    ('¿Cuál es la dirección?', 'datos_del_negocio'),
    ('¿A qué hora abren?', 'datos_del_negocio'),
    ('¿Abren los domingos?', 'datos_del_negocio'),
    ('¿Tienen WhatsApp?', 'datos_del_negocio'),
    ('¿Cómo compro?', 'como_comprar'),
    ('¿Cómo hago un pedido?', 'como_comprar'),
]

# Seguimientos en el panel: (consulta anterior, pregunta, período esperado o None
# si debe ir al modelo).
SEGUIMIENTOS = [
    ('ventas_periodo', '¿Y el mes pasado?', 'mes_anterior'),
    ('ventas_periodo', '¿y ayer?', 'ayer'),
    ('ventas_periodo', 'Y la semana pasada', 'semana_anterior'),
    ('finanzas_periodo', '¿Lo mismo pero de este año?', 'anio'),
    ('top_productos', '¿Y esta semana?', 'semana'),
    ('ventas_periodo', '¿Y el mes pasado y el anterior?', None),
    ('ventas_periodo', '¿Y de Laura?', None),
    ('ventas_periodo', '¿Y los gastos del mes pasado?', None),
    ('productos_bajo_stock', '¿Y el mes pasado?', None),
    ('ventas_periodo,finanzas_periodo', '¿Y el mes pasado?', None),
]


# Preguntas compuestas: una consulta por parte o por período, en orden.
COMPUESTAS = [
    ('¿Cuánto vendí hoy y qué está agotado?',
     [('ventas_periodo', {'periodo': 'hoy'}), ('productos_bajo_stock', {})]),
    ('¿Cuánto me deben y cuánto cobré este mes?',
     [('cartera_pendiente', {}), ('cobros_recibidos', {'periodo': 'mes'})]),
    ('¿Cuánto vendí hoy y ayer?',
     [('ventas_periodo', {'periodo': 'hoy'}), ('ventas_periodo', {'periodo': 'ayer'})]),
    ('¿Cuánto vendí este mes y el mes pasado?',
     [('ventas_periodo', {'periodo': 'mes'}), ('ventas_periodo', {'periodo': 'mes_anterior'})]),
    ('Compara mis ventas de este mes y el mes pasado', [('comparativo_ventas', {'periodo': 'mes'})]),
    ('¿Cuánto vendí y cuánto gasté este mes?',
     [('ventas_periodo', {'periodo': 'mes'}), ('finanzas_periodo', {'periodo': 'mes'})]),
    ('¿Qué está agotado, qué debo comprar y cuánto vale el inventario?',
     [('productos_bajo_stock', {}), ('sugerencia_reorden', {}), ('resumen_inventario', {})]),
    ('¿Cómo está el taller y qué seguimientos del taller tengo pendientes?',
     [('taller_estado', {}), ('taller_seguimientos', {})]),
    ('ingresos y egresos del mes', [('finanzas_periodo', {'periodo': 'mes'})]),
]

# Seguimientos con nombre: (consulta anterior, pregunta, params esperados o None).
SEGUIMIENTOS_NOMBRE = [
    ('cliente_historial', '¿Y de Laura Gómez?', {'cliente': 'Laura Gómez'}),
    ('cliente_historial', '¿y qué tal Juan?', {'cliente': 'Juan'}),
    ('producto_detalle', '¿Y el mouse inalámbrico?', {'producto': 'mouse inalámbrico'}),
    ('taller_casos', '¿y el de Marta?', {'texto': 'Marta'}),
    ('cliente_historial', '¿Y los gastos?', None),
    ('cliente_historial', '¿Y el mes pasado?', None),
    ('ventas_periodo', '¿Y de Laura?', None),
]
